# Helix Language Configs
# Belongs in ~/.config/helix/languages.toml

[[language]]
name = "go"
formatter = { command = "goimports" }

[[language]]
name = "hcl"
auto-format = true
formatter = { command = "hclfmt", args = [] }
