#!/bin/bash

# put this in /usr/local/bin or somewhere else on $PATH

echo -n "deleting stopped containers... "
docker rm $(docker ps -a -q) 1>/dev/null 2>&1 || true
echo "done."

echo -n "deleting untagged images... "
docker rmi $(docker images | grep "^<none>" | awk "{print $3}") 1 > /dev/null 2>&1 || true
echo "done."
